import { NextResponse } from 'next/server';
import { spawn } from 'child_process';
import path from 'path';
import fs from 'fs/promises';

// Types
type DastRequest = {
  targetUrl: string;
};

export async function POST(req: Request) {
  try {
    const body: DastRequest = await req.json();
    const { targetUrl } = body;

    if (!targetUrl || (!targetUrl.startsWith('http://') && !targetUrl.startsWith('https://'))) {
      return NextResponse.json({ error: 'Please provide a valid URL starting with http:// or https://' }, { status: 400 });
    }

    console.log(`[DAST] Initiating dynamic scan for ${targetUrl}...`);

    const pythonScriptPath = path.join(process.cwd(), 'python_tools', 'security_scanner.py');
    const publicDir = path.join(process.cwd(), 'public');
    
    // Ensure public dir exists for PDF export
    await fs.mkdir(publicDir, { recursive: true });

    // Execute Python Scanner headless
    const pythonProcess = spawn('python', [pythonScriptPath, targetUrl], { cwd: process.cwd() });

    let logs = '';
    let errorLogs = '';

    pythonProcess.stdout.on('data', (data) => { logs += data.toString(); });
    pythonProcess.stderr.on('data', (data) => { errorLogs += data.toString(); });

    const exitCode = await new Promise((resolve) => {
      pythonProcess.on('close', resolve);
    });

    if (exitCode !== 0) {
      console.error("[DAST] Python execution failed:", errorLogs);
      return NextResponse.json({ error: 'Dynamic scanning process failed.', details: errorLogs }, { status: 500 });
    }

    // Read the output JSON generated by the scanner
    const jsonOutputPath = path.join(process.cwd(), 'scan_results.json');
    const pdfOutputPath = path.join(process.cwd(), 'security_assessment_report.pdf');
    const publicPdfPath = path.join(publicDir, 'security_report.pdf');

    let scanData;
    try {
        const fileContent = await fs.readFile(jsonOutputPath, 'utf-8');
        scanData = JSON.parse(fileContent);
    } catch(err) {
        return NextResponse.json({ error: 'Failed to read vulnerability payload from scanner.' }, { status: 500 });
    }

    // Move PDF to public folder so the user can download it via href
    try {
        await fs.rename(pdfOutputPath, publicPdfPath);
        scanData.pdfReportAvailable = true;
    } catch(err) {
        console.warn("[DAST] PDF report was not moved or generated successfully.");
        scanData.pdfReportAvailable = false;
    }

    console.log(`[DAST] Scan complete for ${targetUrl}`);
    
    return NextResponse.json(scanData);

  } catch (error: any) {
    console.error("[DAST] Fatal Analyze Error:", error);
    return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
  }
}
